### ISSUE TITLE
Ermittlung fehlender Slots durch den Server

### ISSUE THREAD

**Issue by jcaumann** [gematik/ISiK-Terminplanung#102]
Für die Umsetzung der $book-Operation ist die folgende Vorgabe definiert: "Im Falle dass ein Appointment keine Referenz auf ein oder mehrere Slots enthält, MUSS der Server die benötigten Slots auf Basis der Referenz auf Schedule, sowie dem Start- und Endzeitpunkt im Appointment ermitteln."

FRAGE(N): Das Element "slot" hat die Kardinalität 0..*. Warum reicht hier nicht die Angabe von Start- und Endzeitpunkt? Ist damit gemeint, dass der Server sich einen passenden Slot "bastelt" (zB wenn er keinen findet oder keinen Zugriff auf die entsprechende Datenbank hat) und dann persistiert oder kann der auch inline übertragen werden?

_Originally posted by @jcaumann in https://github.com/gematik/spec-ISiK-Terminplanung/pull/90#discussion_r1211731739_

**Comment by f-peverali** [comment]
@alexzautke wie ist di slot Cardinality Min 0 da gedacht?

**Comment by alexzautke** [comment]
@jcaumann @f-peverali Dies war als eine Erleichterung für den Client gedacht, dass dieser nicht die Referenzen für die Slots finden muss, falls der Client sich sicher ist, dass die Slots in dem ausgewählten Zeitraum buchbar sind. Der Server muss die zugehörigen Slots im Zuge der book-Operation finden, belegen durch die Buchung und im Appointment als Referenz zurückgeben.

**Comment by alexzautke** [comment]
>> ``Warum reicht hier nicht die Angabe von Start- und Endzeitpunkt?``

Die Slot-Referenzen würde ich trotzdem zurückgeben lassen, sodass der Termin-Consumer immer davon ausgehen kann, dass diese vorhanden sind. Tatsächlich würde ich zustimmen, dass der Start- und Endzeitpunkt + die Angabe der Länge eines Slots ausreichend wären. Letzteres kann man jedoch nicht angeben, dies war in der damaligen AG jedoch explizit gewünscht.

**Comment by f-peverali** [comment]
Danke, @alexzautke. Passt für mich und ich schließe das.
