### ISSUE TITLE
Broken link Konformitätserklärung (CapabilityStatement)

### ISSUE THREAD

**Issue by abiernat-corp** [gematik/ISiK-Terminplanung#114]
Auf der Seite https://simplifier.net/guide/isik-terminplanung/ImplementationGuide-markdown-Datenobjekte-CapabilityStatement?version=current findet sich bei 

> Erfüllung der Mindestanforderungen des [Moduls "Basis"](https://simplifier.net/guide/ImplementierungsleitfadenISiK-> Basismodul/Einfuehrung) erfoderlich: 

ein broken link.
```[tasklist]
### Tasks
- [x] Stufe 2
- [x] Stufe 3
```

**Comment by f-peverali** [comment]
@abiernat-cerner, vielen Dank für die Hinweise.
