### ISSUE TITLE
Falscher link ISiKMedizinischeBehandlungseinheit (HealthcareService)

### ISSUE THREAD

**Issue by abiernat-corp** [gematik/ISiK-Terminplanung#115]
Der Link https://simplifier.net/guide/isik-terminplanung/I-markdown-Datenobjekte-ISiKMedizinischeBehandlungseinheitHealthcareService?version=current im Titel zeigt auf die falsche Seite http://hl7.org/fhir/communication.html. Korrekt sollte hier https://hl7.org/fhir/R4/healthcareservice.html sein.
```[tasklist]
### Tasks
- [x] Stufe 2
- [x] Stufe 3
```

**Comment by f-peverali** [comment]
@abiernat-cerner, vielen Dank für die Hinweise.
