### ISSUE TITLE
Link Falsch - inhalt zu klären

### ISSUE THREAD

**Issue by f-peverali** [gematik/ISiK-Terminplanung#116]
https://github.com/gematik/spec-ISiK-Terminplanung/blob/c38e9ea389dd2d2aec8df9b5c7534bcbe82cf37c/ImplementationGuide/markdown/Datenobjekte/ISiKMedizinischeBehandlungseinheitHealthcareService.md?plain=1#L61

Hier ist offensichtlich ein falscher Link.
Ist auch inhaltlich zu klären. Es gibt keinen content-mode in Datenobjekt Valueset, dafür aber in Datenobjekt Codesystem. Dennoch fraglich, ob das hier richtig wäre.

Entscheidende Frage war hier zunächst in Hinblick auf "Entsprechend verwendete Kataloge müssen als CodeSystem- und ValueSet-Ressourcen exponiert werden" -> wie müssen sie Exponiert werden?  Dies auch relevant in Blick auf Testing - auch für das $book-Szenario (FYI @alexey-tschudnowsky ).

**Comment by f-peverali** [comment]
@alexzautke kannst Du hier ahnen, ob und was hier schief ist?

**Comment by alexzautke** [comment]
Ich denke damit ist der Parameter "context-type-value" auf ValueSet gemeint. Mit diesem Parameter kann ich alle ValueSets finden die im Kontext "Appointment" relevant sind.
