### ISSUE TITLE
HTTP Code definieren?

### ISSUE THREAD

**Issue by f-peverali** [gematik/ISiK-Terminplanung#121]
https://github.com/gematik/spec-ISiK-Terminplanung/blob/c38e9ea389dd2d2aec8df9b5c7534bcbe82cf37c/Resources/input/fsh/ISiKBookOperation.fsh#L44

1) Momentan bleibt undefiniert, was im erfolgsfall als HTTP-Code zurückzugeben ist.

@alexzautke was sagst Du? Fehlt hier ggf. 200 oder 201?

2)  Für den Bad request muss gf. auch nachgebessert werden - siehe folgenden Hinweis (von @alexey-tschudnowsky ):

Terminplanung: "Invalide Appointment-Ressourcen MÜSSEN mit einer OperationOutcome und dem Status Code HTTP 400 - Bad Request abgewiesen werden"

Basismodul: 
"Falls die im Dokumenten-Bundle enthaltene Patient-Ressource und/oder Encounter-Ressource nicht anhand der Business-Identifier oder anderer Matching-Kriterien im empfangenden System gefunden werden kann (d.h. der Patient oder der Encounter existiert im empfangenden System noch nicht), MUSS als Antwort der HTTP Status Code "422 - Unprocessable Entity" zurückgegeben werden."

-> ggf. wäre 422 auch bei der Terminplanung zutreffender (ggf. ein Breaking Change, hat daher Zeit und sollte diskutiert werden)

**Comment by alexzautke** [comment]
@f-peverali Der Satz bezog sich auf die Syntax. Wir können es aber gerne in zwei Teile aufteilen: 1. Syntax-Fehler -> HTTP 400, 2. Semantik-Fehler -> HTTP 422.

**Comment by f-peverali** [comment]
ist für die Terminplanung hiermit gelöst: https://github.com/gematik/spec-ISiK-Terminplanung/pull/143
Für die Basis neues Ticket erstellt: https://github.com/gematik/spec-ISiK-Basismodul/issues/308
