### ISSUE TITLE
kein rendering

### ISSUE THREAD

**Issue by f-peverali** [gematik/ISiK-Terminplanung#159]
https://github.com/gematik/spec-ISiK-Terminplanung/blob/75c493183e9c9459031ff689df2481b2e7ef4c1b/Resources/input/fsh/ISiKTerminplanungCapabilityStatement.fsh#L221

Rendering Issue: warum auf folgender Seite nicht zu sehen? https://simplifier.net/guide/Implementierungsleitfaden-ISiK-Modul-Terminplanung-Stufe-3/ImplementationGuide-markdown-Datenobjekte-CapabilityStatement?version=current

[PTDATA-784]

**Comment by alexzautke** [comment]
Wird mit dem nächsten Simplifier-Release (nächste Woche) sichtbar sein.
