### ISSUE TITLE
💡 [REQUEST] - Termine verschieben

### ISSUE THREAD

**Issue by andreas-hempel** [gematik/ISiK-Terminplanung#169]
### Target Date

06 2024

### Summary

In der Spezifikation https://simplifier.net/guide/isik-terminplanung-v3/ImplementationGuide-markdown-Datenobjekte-Operations?version=current steht zum Thema Termine verschieben der folgende Absatz:

"Für die vorliegende Spezifikation ist die Verschiebung eines Termin eins zwei-stufiger Prozess, bei dem ein Termin storniert und ein neuer Termin neu gebucht wird. Dieser Parameter repräsentiert die Ressourcen-Id des stornierten Appointments. Der uri-Parameter kann eine absoulte URL enthalten, Server SOLLEN jedoch nur Termine für ihre eigene Domäne verwalten. Im neu-angelegten Appointment MUSS eine Reference auf den abgesagten Termin hinterlegt werden (vgl. Appointment.extension:replaces). Der Status der abgesagten Ressource MUSS durch den Server angepasst werden."

Es wäre besser wenn die Möglichkeit geschaffen wird, Termine auch über eine Aktualisierung der Appointment Ressource zu verschieben. Diese Funktionalität ist aktuell verboten:

https://simplifier.net/guide/isik-terminplanung-v3/ImplementationGuide-markdown-Datenobjekte-Operations?version=current#aktualisierung-absage-eines-termins.

Leider lässt sich im Implementierungsleitfaden keine Begründung finden, warum eine Terminverschiebung immer ein zweistufiger Prozess sein muss. Es kann passieren das die Stornierung erfolgreich funktioniert, die Neu-Anlage dann aber nicht mehr funktioniert. Egal in welcher Reihenfolge die Verschiebung erfolgt besteht immer das Risiko ein Inkonsistenz. Erfolgt die Verschiebung über ein Update der Appointment Ressource ist das ausgeschlossen.

### Common Examples

Termin durch den Patienten verschieben und Inkonsistenz vermeiden.

### Drawbacks

aktuell keine bekannt

**Comment by alexzautke** [comment]
Hallo @andreas-hempel,

vielen Dank für den Hinweis, dass in der aktuellen Fassung es nicht klar hervorgeht, dass das die Terminverschiebung nur akzeptiert wird durch den Server, wenn der Termin verfügbar ist. Dies Inkonsistenz sollte unbedingt vermieden werden.

>> Leider lässt sich im Implementierungsleitfaden keine Begründung finden, warum eine Terminverschiebung immer ein zweistufiger Prozess sein muss. 

Diesen Teil besprechen wir gerade im ISiK-Team. Wir kommen nochmal darauf zurück, mehr demnächst hier: https://chat.fhir.org/#narrow/stream/287581-german.2Fisik/topic/.5BTermin.5D.20Terminverschiebung.20verstehen

**Comment by alexzautke** [comment]
Änderungen bzgl. der Terminverschiebung sind in Stufe 4 eingeflossen. Falls Rückfragen bestehen, gerne nochmal das Ticket aufmachen.

**Comment by levinalex-samedi** [comment]
Die Spezifikation sagt nun (https://simplifier.net/guide/isik-terminplanung-v4/ImplementationGuide-markdown-Datenobjekte-Operations?version=current)

> Bei Terminverschiebungen (keine Terminabsage!) kann ein Appointment mit einem angepassten Zeitfenster in diesem Parameter übergeben werden. Appointment-Ressourcen, die dem Termin-Repository bekannt sind unter der im Appointment enthaltenen id, MÜSSEN durch das Termin-Repository geupdatet werden unter Beibehaltung der id.

Die exakte Semantik von "geupdated" ist mir etwas unklar. Ich lese diesen Absatz als ein UPDATE im Sinn von [FHIR 3.1.0.4](https://www.hl7.org/fhir/R4/http.html#update). Das heisst, dass die operation sämtliche Attribute der existierenden Appointment-Ressource erhalten muss. Nicht übermittelte Attribute des existierenden Appointments würden durch das update entfernt werden. PATCH-Semantik wird nicht unterstützt, korrekt?

**Comment by alexzautke** [comment]
Ja, korrekt. Der Client übermittelt hier die vollständige Ressource.
