### ISSUE TITLE
Identitäten für die Terminplanung

### ISSUE THREAD

**Issue by alexzautke** [gematik/ISiK-Terminplanung#2]
Als Primärsystemhersteller eines Krankenhausinformationssystem möchte ich wissen, welche Identität (z.B. Belegarzt o. Patient) einen Termin im KIS bucht, um den jeweiligen Prozess im jeweiligen Kontext zu starten.

- [ ] Ein Termin ist mit einer Identität verknüpft.

**Comment by ylboerner** [comment]
Fast Duplikat von https://github.com/gematik/ISiK-Terminplanung/issues/5
