### ISSUE TITLE
Kardinalität inkonsistent (gerendert) (Kommentierung Stufe 3 -> TC)

### ISSUE THREAD

**Issue by f-peverali** [gematik/ISiK-Terminplanung#86]
Die Kardinalität (bzw. das Rendering in Simplifier) muss korrigiert werden.

---

ursprüngliche Anfrage:

Hier sind drei Slices, wobei der Slice “AkteurPatient” die Kard. 1..* hat. Zusätzlich hat auch das das actor-Element ohne Slice eine Kard. von 1..1. Das ist in sich inkonsistent → besser: participant nur Kard. 1..* und Slice nur bei actor mit AkteurPatient Kard. 1..1 (<- da nur ein Pat. pro Termin?).

Zusätzlich sehen die Slices nur das Element status als Pflicht vor.

---

FYI @markus020
```[tasklist]
### Tasks
- [ ] PTDATA-681
```

**Comment by f-peverali** [comment]
@alexzautke bin mir nicht sicher, ob das hier ein Problem in simplifier ist (Rendering) oder in sushi (Kompilierung der Slices), könntest du Dir das bitte nochmal anschauen?

**Comment by alexzautke** [comment]
Das Rendering ist hier nicht optimal. Wie vorgeschlagen könnte man in den Slices selbst noch die Kardinalität sowie das (bisher nicht vorhandene) MS-Flag von .actor (inkl. display auf 1..1 und MS) und .status anpassen. Generell erbt der Slice dies von den (nicht-geslicten) Elementen darüber. Das Rendering zeigt dies jedoch nicht an, man muss hier genau das Profil lesen.

"da nur ein Pat. pro Termin?": Hier war ich mir bei der Gestaltung des Profils auch unsicher und hab es erstmal auf 1..* gelassen. Können wir gerne nochmal besprechen.

**Comment by f-peverali** [comment]
@alexzautke bist du hier weiter dran? Ist da beim branching etwas schiefgelaufen (daher die PRs "closed")?

**Comment by alexzautke** [comment]
@f-peverali Sorry, hatte vergessen hier ein Update zu geben. Ich habe dieses Ticket zusammen mit @patrick-werner getestet. Zusammenfassung: Die Kardinalität lässt sich in FSH nicht überschreiben, da der SUSHI Compiler hier merkt, dass die Kardinalität im Differential doppelt vorhanden wäre (1. Im Slice-Intro für Participant und 2. in den Slices selbst). Zudem kopiert der Snapshot-Generator in .NET als auch in Java diese Kardinalitäten in die Slices.

TLDR: Ja, es ist schwierig zu lesen, technisch aber korrekt.

**Comment by alexzautke** [comment]
Ich kann gerne ein Ticket einreichen bei Firely um hier das Rendering ggf. zu optimieren.

**Comment by alexzautke** [comment]
@f-peverali Bis auf weiteres können wir hier nichts machen, daher wäre mein Vorschlag das Ticket zu schließen. In der Validierung werden die korrekten Kardinalitäten überprüft, daher können wir davon ausgehen, dass es technisch korrekt ist.

**Comment by f-peverali** [comment]
@alexzautke, dann vielleicht zumindest einen Kommentar dazu im Element 'Participant', um die derzeitige View/rendering zu erläutern und  vor allem die eigentliche Intention?
