### ISSUE TITLE
Meta.tag bei Appointment status 'accepted'

### ISSUE THREAD

**Issue by f-peverali** [gematik/ISiK-Terminplanung#94]
https://github.com/gematik/spec-ISiK-Terminplanung/blob/39823ab3d1a842ec281e93e48f34ed7acf374253/ImplementationGuide/markdown/Datenobjekte/ISiKTerminAppointment.md?plain=1#LL55C93-L55C196

> Falls das Datenobjekt dauerhaft in das Termin Repository gespeichert wird, MUSS der Tag entfernt werden

-> Sollte das mit einer accept-Antwort durch das Termin-Repository i.d.R. schon geschehen sein? Dann ggf. hier so formulieren und die Beispiele in Operations.md anpassen.

@jcaumann , was denkst Du?

**Comment by pavlodyban** [comment]
Ich weiß nicht, ob der Tag unbedingt entfernt werden muss. In allen Systemen muss unterschieden werden, ob der Termin intern (im KIS) oder extern (durch ein Zuweiser-/Patientenportal) vergeben wurde. Alleine für die visuelle Darstellung oder für die statistische Datenauswertung. Dann ist eine solche Unterscheidung wie dieser Metatag sinnvoll.

**Comment by f-peverali** [comment]
@pavlodyban vielen Dank für den Hinweis

**Comment by alexzautke** [comment]
Wenn ich mich richtig erinnere hatten @lhitc und ich damals dieses Konzept als eine Art Abfragemöglichkeit für den Client gestaltet um zu schauen welches Appointment bereits dauerhaft übernommen wurde und welche noch in diesem Zwischenzustand sich befinden. Dafür gibt es jedoch bestimmt auch geeigneter Konstrukte. Vielleicht sollten wir uns in Richtung einer Liste für die offenen Appointments bewegen?

**Comment by jcaumann** [comment]
> ... In allen Systemen muss unterschieden werden, ob der Termin intern (im KIS) oder extern (durch ein Zuweiser-/Patientenportal) vergeben wurde....
@pavlodyban : Wäre das nicht implizit über den Kalender erkennbar? Meine Annahme wäre, dass die über das Patientenportal buchbaren Temrine in einem eigenen Kalender zusammengefasst sind, der dann exklusiv vom Portal verwaltet wird. Gerade mit Blick auf die Ausgangsfrage von @f-peverali finde ich die Klassifizierung über ein Meta-Tag schwierig, wenn ein Termin "accepted" ist und als Akteur einen Patient und einen Arzt enthält. In diesem Fall wäre der Termin ja vielleicht über das Portal "gebucht" worden, wurde im Rahmen des Workflows aber ggf. durch das KIS "bestätigt" (zB weil dieses dann den Arzt zugeordnet hat). Wurde in einem solchen Fall der Termin durch das Portal oder das KIS "bestätigt", d.h. ist er intern oder extern?

**Comment by f-peverali** [comment]
Stufe 4 Thema

**Comment by pavlodyban** [comment]
> > ... In allen Systemen muss unterschieden werden, ob der Termin intern (im KIS) oder extern (durch ein Zuweiser-/Patientenportal) vergeben wurde....
> > @pavlodyban : Wäre das nicht implizit über den Kalender erkennbar? Meine Annahme wäre, dass die über das Patientenportal buchbaren Temrine in einem eigenen Kalender zusammengefasst sind, der dann exklusiv vom Portal verwaltet wird. Gerade mit Blick auf die Ausgangsfrage von @f-peverali finde ich die Klassifizierung über ein Meta-Tag schwierig, wenn ein Termin "accepted" ist und als Akteur einen Patient und einen Arzt enthält. In diesem Fall wäre der Termin ja vielleicht über das Portal "gebucht" worden, wurde im Rahmen des Workflows aber ggf. durch das KIS "bestätigt" (zB weil dieses dann den Arzt zugeordnet hat). Wurde in einem solchen Fall der Termin durch das Portal oder das KIS "bestätigt", d.h. ist er intern oder extern?

Patientenportale dürfen Termine in den Kalendern mit gemischter Nutzung buchen. In diesen Kalendern finden sich offline und online Termine nebeneinander. Eine Unterscheidung, ob ein Termin online durch den Patienten, online durch den Zuweiser oder offline (vor Ort im Krankenhaus) gebucht wurde, wird aus den prozessualen und statistischen Gründen oft erfragt. Die Annahme, dass die Portale Termine nur in isolierten Kalendern buchen, deckt sich nicht mit der Realität.
Die Quelle der Terminbuchung bleibt auch nach der Bestätigung durch das KIS erhalten. Termine, die über das Patientenportal gebucht wurden, sollen auch weiterhin im KIS so gekennzeichnet sein. Alleine aus den Gründen der Auswertung der Terminquellen und dem Handling der aufzunehmenden Patienten.
Ob man den o.g. Tag für die Klassifizierung der Quelle der Terminbuchung nehmen soll, darüber habe ich keine starke Meinung. Mag sein, dass der vorgeschlagene Tag für eine andere Information besser geeignet ist. Die Entscheidung überlasse ich den FHIR-Experten :)

**Comment by alexzautke** [comment]
@f-peverali Vorschlag: Angleichung an die TC in Basis Stufe 3 mit ähnlichem Wording wie in https://simplifier.net/guide/Implementierungsleitfaden-ISiK-Basismodul-Stufe-3/markdown-UebergreifendeFestlegungen-UebergreifendeFestlegungen-Rest?version=current - Create-Interaktionen, d.h. der Tag kann entfernt werden muss jedoch nicht.
