### ISSUE TITLE
Vorschlag: Der Termin-Requestor KANN durch die Abfrage aller verfügbaren Kalender anschließend alle diesen Kalendern zugeordnetem Slot-Ressourcen abfragen und über diese dann die eigentliche Terminsuche und -buchung ausführen.

### ISSUE THREAD

**Issue by f-peverali** [gematik/ISiK-Terminplanung#96]
Vorschlag: Der Termin-Requestor KANN durch die Abfrage aller verfügbaren Kalender anschließend alle diesen Kalendern zugeordnetem Slot-Ressourcen abfragen und über diese dann die eigentliche Terminsuche und -buchung ausführen.

_Originally posted by @jcaumann in https://github.com/gematik/spec-ISiK-Terminplanung/pull/93#discussion_r1205757056_

**Comment by f-peverali** [comment]
@jcaumann das sieht für mich obsolet aus, oder?

**Comment by jcaumann** [comment]
das war nur ein Vorschlag für die Formulierung und nichts Inhaltliches. Kann ignoriert werden.

**Comment by f-peverali** [comment]
Danke, @jcaumann , dann schließe ich das Issue
