### ISSUE TITLE
Diese Abfrage liefert alle an den Kalender gebundenen Slots, auch die die nicht verfügbar sind. Die Abfrage nach den VERFÜGBAREN Slots wäre: GET https://example.org/fhir/Slot?schedule=<Schedule/ISiKKalenderExample>&status=free

### ISSUE THREAD

**Issue by f-peverali** [gematik/ISiK-Terminplanung#97]
Diese Abfrage liefert alle an den Kalender gebundenen Slots, auch die die nicht verfügbar sind. Die Abfrage nach den VERFÜGBAREN Slots wäre: GET https://example.org/fhir/Slot?schedule=<Schedule/ISiKKalenderExample>&status=free

_Originally posted by @jcaumann in https://github.com/gematik/spec-ISiK-Terminplanung/pull/93#discussion_r1205760699_

**Comment by f-peverali** [comment]
Siehe entsprechende Anfragen in ISiKTerminblockSlot.md und Operations.md

**Comment by alexzautke** [comment]
+1 sollten wir korrigieren
