### ISSUE TITLE
auch wenn es nur ein Beispiel ist, würde ich hier die NEMA DCM Kodierung nehmen:

### ISSUE THREAD

**Issue by f-peverali** [gematik/ISiK-Terminplanung#98]
auch wenn es nur ein Beispiel ist, würde ich hier die NEMA DCM Kodierung nehmen:
n diesem Fall ist auch ein Chaining auf weitere verknüpfte Akteure möglich: `GET https://example.org/fhir/Slot?schedule.actor:HealthcareService.type=http://dicom.nema.org/resources/ontology/DCM|CT`

_Originally posted by @jcaumann in https://github.com/gematik/spec-ISiK-Terminplanung/pull/93#discussion_r1205774253_

**Comment by alexzautke** [comment]
+1, sollten wir wie vorgeschlagen korrigieren
