### ISSUE TITLE
bei der Rückgabe macht dieses Tag aber eigentlich keinen Sinn, da der Empfänger hier aus dem "external" keine Information ziehen kann. Oder etwas doch?

### ISSUE THREAD

**Issue by f-peverali** [gematik/ISiK-Terminplanung#99]
bei der Rückgabe macht dieses Tag aber eigentlich keinen Sinn, da der Empfänger hier aus dem "external" keine Information ziehen kann. Oder etwas doch?

_Originally posted by @jcaumann in https://github.com/gematik/spec-ISiK-Terminplanung/pull/93#discussion_r1205783664_

**Comment by f-peverali** [comment]
@jcaumann , ist das für dich weiter relevant? Mir fehlt hier der Kontext zum Verständnis. Welches Tag?

**Comment by alexzautke** [comment]
Siehe https://github.com/gematik/spec-ISiK-Terminplanung/issues/94#issuecomment-1569121299 für Begründung wieso der Tag sinnvoll ist

**Comment by alexzautke** [comment]
Für mich wäre es keine gute Lösung wenn der Server eine veränderte Ressource (ohne Tag) zurückgibt im Vergleich zu der Ressource die im Termin-Repository abgelegt wurden ist.

**Comment by f-peverali** [comment]
Danke, @alexzautke , ich schließe das Ticket.
